[package]
authors = ["kflange <zknsftk1msrk@gmail.com>"]
edition = "2018"
name = "example-actix-web"
version = "0.3.0"
[dependencies]
actix-web = "2"
actix-rt = "1"
env_logger = "*"
log = "*"
juniper = "0.14"
serde = {version = "*", features = ["derive"] }
serde_json = "*"
