[package]
authors = ["kflange <zknsftk1msrk@gmail.com>"]
edition = "2018"
name = "example-actix-web"
version = "0.2.0-develop"
[dependencies]
actix-web = "2"
actix-rt = "1"
env_logger = "*"
log = "*"
